name: fix_eyd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter: 
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  intl: ^0.18.1
  sqflite: ^2.3.3
  path: ^1.8.3
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  flutter_markdown: ^0.6.17
  geolocator: ^12.0.0
  geocoding: ^2.0.5
  flutter_local_notifications: ^17.2.3
  permission_handler: ^12.0.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  image_picker: ^1.1.1
  local_auth: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/default_avatar.svg
    - assets/data/pbm_materi.json
